FROM node:16.20.2-bullseye as base

WORKDIR /app

COPY tsconfig*.json ./
COPY package*.json ./

RUN apt-get update && \
  apt install -y curl && \
  npm install -g @nestjs/cli

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
