version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - devnetwork

  node-backend:
    container_name: node-backend
    depends_on:
      - dev-db
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - devnetwork

volumes:
  dbdata:
networks:
  devnetwork:
